### ISSUE TITLE
not an issue - fyi - tensorflow Perceptron : Learnable

### ISSUE THREAD

**Issue by johndpope** [jbrunhuber/neural-net#1]
https://www.tensorflow.org/api_docs/swift/Protocols/Learnable

there's still a few bumps getting local mac project up and running see here for compiler flags - 
https://github.com/tensorflow/swift-models/issues/10

**Comment by johndpope** [comment]
actually not working right.

**Comment by jbrunhuber** [comment]
Hi @johndpope.
Thanks for the information. I'm going to check out Tensorflow after I'm more familiar with the basics.
